Models/Artistas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAppMusicCatalog.Models
{
    public  class Artistas
    {
        
        public Artistas()
        {
            this.Canciones = new HashSet<Canciones>();
        }

        [Key]
        public int artista_id { get; set; }
        [DisplayName("Nombre artista")]
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [StringLength(100, ErrorMessage = "El nombre no puede exceder los 100 caracteres.")]
        public string nombre { get; set; }
        [DisplayName("Nacionalidad")]        
        public Nullable<int> nacionalidad_pais_id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha nacimiento")]
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        [DisplayName("Genero musical")]
        [StringLength(50, ErrorMessage = "El genero musical no puede exceder los 50 caracteres.")]
        public string genero_musical { get; set; }
        [DisplayName("Biografia")]
        [DataType(DataType.MultilineText)]
        public string biografia { get; set; }
        public byte[] imagen { get; set; }
        [DisplayName("Imagen")]
        public string ruta_archivo_imagen { get; set; }

        [DisplayName("URL sitio web")]
        [DataType(DataType.Url)]
        public string url_sitio_web { get; set; }
        [DisplayName("Fecha creacion")]
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        [DisplayName("Fecha modificacion")]
        public Nullable<System.DateTime> fecha_modificacion { get; set; }

        public virtual Paises Paises { get; set; }
        
        public virtual ICollection<Canciones> Canciones { get; set; }
    }
}

Controllers/ArtistasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppMusicCatalog.Models;
using System.IO;
using System.Web.Helpers;
using System.Data.Entity.Validation;

namespace WebAppMusicCatalog.Controllers
{
    [Autorizacion]
    public class ArtistasController : Controller
    {
        private MusicCatalogEntities db = new MusicCatalogEntities();

        // GET: Artistas
        //[Authorize]
        public async Task<ActionResult> Index(string searchString)
        {
            var artistas = db.Artistas.Include(a => a.Paises);

            if (!String.IsNullOrEmpty(searchString))
            {
                artistas = artistas.Where(s => s.nombre.ToUpper().Contains(searchString.ToUpper()));
            }
            return View(await artistas.ToListAsync());
        }       

        // GET: Artistas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artistas artistas = await db.Artistas.FindAsync(id);
            if (artistas == null)
            {
                return HttpNotFound();
            }
            return View(artistas);
        }

        // GET: Artistas/Create
        public ActionResult Create()
        {
            ViewBag.nacionalidad_pais_id = new SelectList(db.Paises, "pais_id", "nombre");
            return View();
        }

        // POST: Artistas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //public async Task<ActionResult> Create([Bind(Include = "artista_id,nombre,nacionalidad_pais_id,fecha_nacimiento,genero_musical,biografia,imagen,ruta_archivo_imagen,url_sitio_web,fecha_creacion,fecha_modificacion")] Artistas artistas)
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Create([Bind(Include = "nombre,nacionalidad_pais_id,fecha_nacimiento,genero_musical,biografia,imagen,ruta_archivo_imagen,url_sitio_web")] Artistas artistas, HttpPostedFileBase ruta_archivo_imagen)
        {
            if (ModelState.IsValid)
            {
                artistas.fecha_creacion = DateTime.Now;
                artistas.fecha_modificacion= DateTime.Now;
                if (ruta_archivo_imagen != null)
                {
                    WebImage img = new WebImage(ruta_archivo_imagen.InputStream);
                    FileInfo imginfo = new FileInfo(ruta_archivo_imagen.FileName);

                    string logoname = Guid.NewGuid().ToString() + imginfo.Extension;
                    img.Resize(50, 50);
                    img.Save("~/Uploads/Artistas/" + logoname);

                    artistas.ruta_archivo_imagen = "/Uploads/Artistas/" + logoname;
                }
                db.Artistas.Add(artistas);
                
                try
                {
                    // Your code...
                    // Could also be before try if you know the exception occurs in SaveChanges
                    await db.SaveChangesAsync();
                    //context.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw;
                }
                return RedirectToAction("Index");
            }

            ViewBag.nacionalidad_pais_id = new SelectList(db.Paises, "pais_id", "nombre", artistas.nacionalidad_pais_id);
            return View(artistas);
        }
       
        // GET: Artistas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artistas artistas = await db.Artistas.FindAsync(id);
            if (artistas == null)
            {
                return HttpNotFound();
            }
            ViewBag.nacionalidad_pais_id = new SelectList(db.Paises, "pais_id", "nombre", artistas.nacionalidad_pais_id);
            return View(artistas);
        }
        
        // POST: Artistas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit([Bind(Include = "artista_id,nombre,nacionalidad_pais_id,fecha_nacimiento,genero_musical,biografia,imagen,ruta_archivo_imagen,url_sitio_web,fecha_creacion,fecha_modificacion")] Artistas artistas, HttpPostedFileBase ruta_archivo_imagen)
        {
            if (ModelState.IsValid)
            {                
                artistas.fecha_modificacion = DateTime.Now;
                db.Entry(artistas).State = EntityState.Modified;

                if (ruta_archivo_imagen == null)
                {
                    Artistas artistas2 = await db.Artistas.FindAsync(artistas.artista_id);
                    artistas.ruta_archivo_imagen = artistas2.ruta_archivo_imagen;
                }
                
                if (ruta_archivo_imagen != null)
                {                    
                    WebImage img = new WebImage(ruta_archivo_imagen.InputStream);
                    FileInfo imginfo = new FileInfo(ruta_archivo_imagen.FileName);

                    //string logoname = ruta_archivo_imagen.FileName + imginfo.Extension;
                    string logoname = ruta_archivo_imagen.FileName;
                    img.Resize(300, 200);

                    if (System.IO.File.Exists(Server.MapPath("~/Uploads/Artistas/" + logoname)))
                    {
                        System.IO.File.Delete(Server.MapPath("~/Uploads/Artistas/" + logoname));
                    }

                    img.Save("~/Uploads/Artistas/" + logoname);

                    artistas.ruta_archivo_imagen = "/Uploads/Artistas/" + logoname;
                }

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.nacionalidad_pais_id = new SelectList(db.Paises, "pais_id", "nombre", artistas.nacionalidad_pais_id);
            return View(artistas);
        }

        // GET: Artistas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artistas artistas = await db.Artistas.FindAsync(id);
            if (artistas == null)
            {
                return HttpNotFound();
            }
            return View(artistas);
        }

        // POST: Artistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Artistas artistas = await db.Artistas.FindAsync(id);
            db.Artistas.Remove(artistas);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Artistas/Create.cshtml
@model WebAppMusicCatalog.Models.Artistas

@{
    ViewBag.Title = "Crear Artista";
}

<h2>Crear</h2>

@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Create", "Artistas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Artistas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nacionalidad_pais_id, "nacionalidad_pais_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("nacionalidad_pais_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nacionalidad_pais_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_nacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_nacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_nacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genero_musical, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.genero_musical, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.genero_musical, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.biografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.biografia, new { htmlAttributes = new { @class = "form-control", rows = "8", cols = "20" } })
                @Html.ValidationMessageFor(model => model.biografia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.ruta_archivo_imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ruta_archivo_imagen, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="ruta_archivo_imagen" accept=".png,.jpg,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.ruta_archivo_imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.url_sitio_web, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url_sitio_web, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url_sitio_web, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.fecha_creacion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fecha_creacion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fecha_creacion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fecha_modificacion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fecha_modificacion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fecha_modificacion, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atras a Lista", "Index")
</div>

Views/Artistas/Delete.cshtml
@model WebAppMusicCatalog.Models.Artistas

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Esta seguro de eliminar el registro?</h3>
<div>
    <h4>Artistas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_nacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_nacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genero_musical)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genero_musical)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.biografia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.biografia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ruta_archivo_imagen)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.ruta_archivo_imagen)*@
            <img class="img-responsive" src="@Model.ruta_archivo_imagen" width="200" height="200" /> @*/*** Dikkat *****/*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url_sitio_web)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url_sitio_web)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_creacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_creacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_modificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_modificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paises.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paises.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Atras a Lista", "Index")
        </div>
    }
</div>

Views/Artistas/Details.cshtml
@model WebAppMusicCatalog.Models.Artistas

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Artistas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_nacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_nacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genero_musical)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genero_musical)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.biografia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.biografia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ruta_archivo_imagen)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.ruta_archivo_imagen)*@
            <img class="img-responsive" src="@Model.ruta_archivo_imagen" width="200" height="200" /> @*/*** Dikkat *****/*@

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url_sitio_web)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url_sitio_web)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_creacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_creacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_modificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_modificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paises.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paises.nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.artista_id }) |
    @Html.ActionLink("Atras a la Lista", "Index")
</p>

Views/Artistas/Edit.cshtml
@model WebAppMusicCatalog.Models.Artistas

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Edit", "Artistas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Artistas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.artista_id)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nacionalidad_pais_id, "nacionalidad_pais_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("nacionalidad_pais_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nacionalidad_pais_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_nacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_nacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_nacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genero_musical, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.genero_musical, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.genero_musical, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.biografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.biografia, new { htmlAttributes = new { @class = "form-control", rows = "8", cols = "20" } })
                @Html.ValidationMessageFor(model => model.biografia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ruta_archivo_imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @*<img src="@Url.Content(Model.url_sitio_web)" height="150" width="150" />*@
                <img class="img-responsive" src="@Model.ruta_archivo_imagen" width="150" height="150" /> @*/*** Dikkat *****/*@
                <input type="file" name="ruta_archivo_imagen" accept=".png,.jpg,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.ruta_archivo_imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.ruta_archivo_imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ruta_archivo_imagen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ruta_archivo_imagen, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.url_sitio_web, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url_sitio_web, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url_sitio_web, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.fecha_creacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_creacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_creacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_modificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_modificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_modificacion, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atras a Lista", "Index")
</div>

Views/Artistas/Index.cshtml
@model IEnumerable<WebAppMusicCatalog.Models.Artistas>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<form asp-controller="Artistas" asp-action="Index">
    <p>
        <label>Artista: <input type="text" name="SearchString" /></label>
        <input type="submit" value="Buscar" />
    </p>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
         
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha_nacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.genero_musical)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.biografia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ruta_archivo_imagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url_sitio_web)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha_creacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha_modificacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paises.nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @*@Html.DisplayFor(modelItem => item.nombre)*@
            @Html.ActionLink(item.nombre,
    "Index", "Canciones",
    new { artistaId = item.artista_id }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha_nacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.genero_musical)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.biografia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.imagen)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.ruta_archivo_imagen)*@
            <img class="img-responsive" src="@item.ruta_archivo_imagen" width="200" height="200" /> @*/*** Dikkat *****/*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.url_sitio_web)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha_creacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha_modificacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paises.nombre)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.artista_id }) |
            @Html.ActionLink("Detalle", "Details", new { id=item.artista_id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.artista_id })
        </td>
    </tr>
}

</table>